export const skillsItems = [
  "html5",
  "css3",
  "JavaScript",
  "TypeScript ",
  "React.js",
  "Next.js",
  "jQuery",
  "sass/scss",
  "Bootstrap",
  "Tailwind",
  "Jest",
  "AJAX",
  "JSON",
  "Git",
  "GitHub",
];
export const skillsIcon = [
  "/svg/html.svg",
  "/svg/css.svg",
  "/svg/js.svg",
  "/svg/ts.svg",
  "/svg/react.svg",
  "/svg/next.svg",
  "/svg/bootsrtap.svg",
  "/svg/tailwind.svg",
  "/svg/sass.svg",
  "/svg/jQuery.svg",
  "/svg/jest.svg",
  "/svg/json.svg",
  "/svg/git.svg",
  "/svg/github.svg",
];