export const skillsItems = [
  "html5",
  "css3",
  "JavaScript",
  "TypeScript ",
  "React.js",
  "Next.js",
  "jQuery",
  "sass/scss",
  "Bootstrap",
  "Tailwind",
  "JEST",
  "AJAX",
  "JSON",
  "Git",
  "GitHub",
];
export const skillsIcon = [
  "/svg/html.svg",
  "/svg/css.svg",
  "/svg/js.svg",
  "/svg/ts.svg",
  "/svg/react.svg",
  "/svg/next.svg",
  "/svg/bootsrtap.svg",
  "/svg/tailwind.svg",
  "/svg/sass.svg",
  "/svg/jQuery.svg",
  "/svg/jest.svg",
  "/svg/json.svg",
  "/svg/git.svg",
  "/svg/github.svg",
];
export const list = [
  [
    "1",
    "Dental booking website",
    "A simple design dentelcare booking website with admin Dashboard",
    "Html 5 , Css 3 , Javascript , react and Tailwind , API",
    "https://github.com/fares12358/BookingDentist",
    "https://booking-dentist.vercel.app/",
    "/images/dentist.webp",
    "5",
    "1",
  ],
  [
    "2",
    "Travel App",
    "A simple design for responsive travel web site",
    "Html 5, Css 3, typescript , tailwind , next ,react",
    "https://github.com/fares12358/Travel-app",
    "https://travel-app-red-seven.vercel.app/",
    "/images/travel-app.webp",
    "0",
    "2",
  ],
  [
    "3",
    "Bondi landing page",
    "A simple Bondi design for responsive web site",
    "Html 5, Css 3, Javascript and bootstrap",
    "https://github.com/fares12358/new-Bondi",
    "https://fares12358.github.io/new-Bondi/",
    "/images/Untitled (1).webp",
    "1",
    "3",
  ],
  [
    "4",
    "Mobile back cover",
    "A simple e-commerce design for mobile cover",
    "Html 5, Css 3, Javascript , react and bootstrap , JSON , APIs",
    "https://github.com/fares12358/online-shop-with-react",
    "https://fares12358.github.io/online-shop-with-react/",
    "/images/backApp.webp",
    "2",
    "4",
  ],
  [
    "5",
    "island landing page",
    "A landing pag for travel island web site",
    "Html 5, Css 3, Javascript and bootstrap",
    "https://github.com/fares12358/island",
    "https://fares12358.github.io/island/",
    "/images/island.webp",
    "3",
    "5",
  ],
  [
    "6",
    "404 Page",
    "A 404 Error not found page design",
    "Html 5, Css 3, Javascript and bootstrap",
    "https://github.com/fares12358/Xcompany",
    "https://fares12358.github.io/Xcompany/",
    "/images/Untitled.webp",
    "4",
    "0",
  ],
];